import {
  KEY_DELETE,
  KEY_PREV_WORD,
  KEY_SPACE,
  WORD_LISTS,
  computeResult,
  coreWord,
  type Keystroke,
  type ResultSubmission,
  type TestResult,
} from "@keystride/engine";

/** Hard ceiling — the fastest verified humans peak around 300 wpm on short tests. */
export const MAX_WPM = 350;
/** Characters inside any 1-second window (~420 wpm burst). */
const MAX_CHARS_PER_SECOND = 35;
/** Human inter-key intervals vary a lot; bots are metronomic. */
const MIN_INTERVAL_COV = 0.15;
/** Share of near-simultaneous keystrokes before it looks injected. */
const MAX_TINY_INTERVAL_SHARE = 0.3;
const TINY_INTERVAL_MS = 8;

export type Verdict =
  | { ok: true; result: TestResult; flagReason: null }
  | { ok: true; result: TestResult; flagReason: string }
  | { ok: false; error: string };

const PUNCT = /^["(]?(.*?)(?:'s)?[.,?!;:]?[")]?$/;

/** Checks a displayed word could have come from the generator for this config. */
function isValidWord(word: string, sub: ResultSubmission, list: ReadonlySet<string>): boolean {
  if (sub.config.numbers && /^[1-9]\d{0,3}$/.test(word)) return true;
  if (!sub.config.punctuation) return list.has(word);
  const core = PUNCT.exec(word)?.[1] ?? word;
  if (sub.config.numbers && /^[1-9]\d{0,3}$/.test(core)) return true;
  return list.has(core) || list.has(core.charAt(0).toLowerCase() + core.slice(1));
}

interface Replay {
  typed: string[];
  index: number;
}

/** Rebuilds the typed words from the keystroke log alone. */
export function replay(keystrokes: readonly Keystroke[]): Replay | null {
  const typed: string[] = [""];
  let index = 0;
  for (const k of keystrokes) {
    if (k.key === KEY_SPACE) {
      if (!typed[index]) return null; // app never commits an empty word
      index++;
      typed[index] ??= "";
    } else if (k.key === KEY_DELETE) {
      if (!typed[index]) return null;
      typed[index] = typed[index].slice(0, -1);
    } else if (k.key === KEY_PREV_WORD) {
      if (index === 0 || typed[index]) return null;
      index--;
    } else if ([...k.key].length === 1) {
      typed[index] += k.key;
    } else {
      return null;
    }
  }
  return { typed, index };
}

function coefficientOfVariation(values: number[]): number {
  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  if (mean === 0) return 0;
  const variance = values.reduce((a, v) => a + (v - mean) ** 2, 0) / values.length;
  return Math.sqrt(variance) / mean;
}

/** Timing plausibility on character keystrokes. Returns a reason when suspicious. */
export function timingFlags(keystrokes: readonly Keystroke[]): string | null {
  const times = keystrokes.filter((k) => k.correct !== null).map((k) => k.t);
  if (times.length < 20) return null;

  const intervals: number[] = [];
  for (let i = 1; i < times.length; i++) intervals.push(times[i] - times[i - 1]);

  if (coefficientOfVariation(intervals) < MIN_INTERVAL_COV) {
    return "keystroke timing too uniform";
  }
  const tiny = intervals.filter((d) => d < TINY_INTERVAL_MS).length / intervals.length;
  if (tiny > MAX_TINY_INTERVAL_SHARE) return "too many simultaneous keystrokes";

  let start = 0;
  for (let end = 0; end < times.length; end++) {
    while (times[end] - times[start] >= 1000) start++;
    if (end - start + 1 > MAX_CHARS_PER_SECOND) return "burst speed not humanly possible";
  }
  return null;
}

/**
 * Verifies a submission and recomputes its result server-side.
 * - `ok: false` → malformed or inconsistent; reject outright.
 * - `flagReason` set → store, but exclude from PBs and leaderboards.
 */
export function verifySubmission(sub: ResultSubmission): Verdict {
  const { config, words, keystrokes, durationMs } = sub;

  // 1. Duration matches the mode.
  if (config.mode === "time" && Math.abs(durationMs - config.amount * 1000) > 1) {
    return { ok: false, error: "duration does not match test length" };
  }
  if (config.mode === "words" && words.length !== config.amount) {
    return { ok: false, error: "word count does not match test length" };
  }

  // 2. Keystroke clock is sane.
  let prevT = 0;
  for (const k of keystrokes) {
    if (!(k.t >= prevT) || k.t > durationMs + 1) {
      return { ok: false, error: "keystroke timestamps out of order" };
    }
    prevT = k.t;
  }

  // 3. Words could have come from our generator.
  const list = new Set<string>(WORD_LISTS[config.language]);
  if (!words.every((w) => isValidWord(w, sub, list))) {
    return { ok: false, error: "unknown words in test" };
  }
  // The generator never repeats a word back-to-back (blocks "a a a a" farming).
  for (let i = 1; i < words.length; i++) {
    const w = coreWord(words[i]);
    if (w === coreWord(words[i - 1]) && !/^\d+$/.test(w)) {
      return { ok: false, error: "word sequence was not generated by the app" };
    }
  }

  // 4. The log alone must reproduce what was typed.
  const r = replay(keystrokes);
  if (!r) return { ok: false, error: "keystroke log is inconsistent" };

  let committed = r.index;
  // Words mode ends without a space when the last word is typed exactly.
  const last = words.length - 1;
  if (config.mode === "words" && r.index === last && r.typed[last] === words[last]) committed = words.length;
  if (committed !== sub.committed) return { ok: false, error: "word progress mismatch" };
  // Only a finished words-mode test may move past the last word.
  if (r.index > words.length || (r.index === words.length && config.mode !== "words")) {
    return { ok: false, error: "typed past the end of the test" };
  }
  for (let i = 0; i < words.length; i++) {
    if ((r.typed[i] ?? "") !== (sub.typed[i] ?? "")) {
      return { ok: false, error: "typed text does not match keystrokes" };
    }
  }

  // 5. Recompute correctness from the replay — never trust client flags.
  const trusted: Keystroke[] = [];
  const cur: string[] = [""];
  let idx = 0;
  for (const k of keystrokes) {
    let correct: boolean | null = null;
    if (k.key === KEY_SPACE) {
      correct = cur[idx] === words[idx];
      idx++;
      cur[idx] ??= "";
    } else if (k.key === KEY_DELETE) {
      cur[idx] = cur[idx].slice(0, -1);
    } else if (k.key === KEY_PREV_WORD) {
      idx--;
    } else {
      correct = k.key === (words[idx] ?? "")[cur[idx].length];
      cur[idx] += k.key;
    }
    trusted.push({ t: k.t, key: k.key, correct });
  }

  const result = computeResult({
    words,
    typed: r.typed.slice(0, words.length),
    committed,
    keystrokes: trusted,
    durationMs,
    config,
  });

  if (result.wpm > MAX_WPM || result.rawWpm > MAX_WPM + 50) {
    return { ok: true, result, flagReason: "speed above human limits" };
  }
  const timing = timingFlags(trusted);
  if (timing) return { ok: true, result, flagReason: timing };
  return { ok: true, result, flagReason: null };
}
